# Generated by Django 5.2.2 on 2025-06-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employ_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(),
        ),
    ]
